### ISSUE TITLE
Neikvæð verð

### ISSUE THREAD

**Issue by hannespetur** [nori/hbv401g-2015v-f1a#2]
Verðin á leikmönnum fer í neikvæðar tölur, og hérna fann ég tilvik þar sem það kom mjög stór neikvæð tala (stærsta neikvæða int talan).

![Neikvæð verð](http://i.imgur.com/sCQT8Cf.png)

**Comment by nori** [comment]
Var að taka vitlausa tölu frá JSON, ætti að vera komið í lag núna. Skv kröfum þurfa verð víst aðeins að ákvarðast af hversu margir spilarar kaupa hann svo ég bætti við playerBought og playerSold í Player sem þið kallið í eftir að leikmaður er keyptur/seldur til þess að hækka/lækka verðið.

**Comment by hannespetur** [comment]
Ok takk, ég bæti því við.
